ISTANBUL_LOCATIONS = {
    "Kadıköy": ["Caddebostan", "Fenerbahçe", "Moda (Caferağa)", "Suadiye", "Bostancı", "Göztepe", "Acıbadem", "Koşuyolu", "Fikirtepe", "Rasimpaşa", "Hasanpaşa", "Erenköy"],
    "Beşiktaş": ["Bebek", "Etiler", "Levent", "Ulus", "Arnavutköy", "Ortaköy", "Akatlar", "Türkali", "Sinanpaşa", "Abbasağa", "Dikilitaş", "Gayrettepe"],
    "Sarıyer": ["İstinye", "Yeniköy", "Tarabya", "Maslak", "Emirgan", "Baltalimanı", "Zekeriyaköy", "Ayazağa", "Reşitpaşa", "Kireçburnu", "Büyükdere", "Rumelihisarı"],
    "Bakırköy": ["Ataköy", "Yeşilköy", "Yeşilyurt", "Florya (Şenlikköy)", "Zuhuratbaba", "Kartaltepe", "Osmaniye", "Cevizlik", "Sakızağacı"],
    "Şişli": ["Nişantaşı (Teşvikiye)", "Harbiye", "Bomonti", "Mecidiyeköy", "Fulya", "Halaskargazi", "Esentepe", "Gülbahar", "Feriköy", "Kurtuluş"],
    "Üsküdar": ["Kuzguncuk", "Beylerbeyi", "Çengelköy", "Kandilli", "Altunizade", "Acıbadem", "Salacak", "Kuleli", "Bulgurlu", "Ünalan"],
    "Beyoğlu": ["Cihangir", "Galata (Bereketzade)", "Karaköy", "Asmalımescit", "Gümüşsuyu", "Tomtom", "Pürtelaş", "Kasımpaşa", "Sütlüce"],
    "Ataşehir": ["Batı Ataşehir", "Atatürk Mah.", "İçerenköy", "Küçükbakkalköy", "Barbaros", "Kayışdağı", "Örnek Mah.", "Fetih"],
    "Maltepe": ["Küçükyalı", "İdealtepe", "Altıntepe", "Bağlarbaşı", "Cevizli", "Zümrütevler", "Başıbüyük", "Fındıklı"],
    "Kartal": ["Kordonboyu", "Atalar", "Dragos (Orhantepe)", "Cevizli", "Petrol İş", "Uğur Mumcu", "Yakacık", "Soğanlık"],
    "Zeytinburnu": ["Kazlıçeşme", "Merkezefendi", "Seyitnizam", "Çırpıcı", "Sümer", "Beştelsiz", "Yeşiltepe"],
    "Fatih": ["Sultanahmet", "Balat", "Fener", "Aksaray", "Çapa (Şehremini)", "Kocamustafapaşa", "Topkapı", "Vefa", "Karagümrük"],
    "Eyüpsultan": ["Göktürk", "Kemerburgaz", "Alibeyköy", "Eyüp Merkez", "Yeşilpınar", "Rami", "Silahtarağa"],
    "Kağıthane": ["Seyrantepe", "Çeliktepe", "Emniyetevleri", "Gültepe", "Hamidiye", "Çağlayan", "Merkez"],
    "Beykoz": ["Acarkent", "Kanlıca", "Anadolu Hisarı", "Kavacık", "Paşabahçe", "Çubuklu", "Görele", "Riva"],
    "Ümraniye": ["Çakmak", "Ihlamurkuyu", "İnkılap", "Atakent", "Armağanevler", "Tantavi", "Yamanevler", "Madenler"],
    "Pendik": ["Kurtköy", "Yenişehir", "Güzelyalı", "Batı Mah.", "Kaynarca", "Çamlık", "Esenyalı"],
    "Küçükçekmece": ["Atakent", "Halkalı", "Cennet", "Kanarya", "Sefaköy", "İnönü", "Cumhuriyet"],
    "Başakşehir": ["Bahçeşehir 1. Kısım", "Bahçeşehir 2. Kısım", "Başak", "Kayaşehir", "Güvercintepe", "Ziya Gökalp"],
    "Bahçelievler": ["Yenibosna", "Şirinevler", "Yaylabaşı", "Kocasinan", "Soğanlı", "Cumhuriyet"],
    "Beylikdüzü": ["Barış Mah.", "Beykent (Adnan Kahveci)", "Yakuplu", "Kavaklı", "Gürpınar", "Dereağzı"],
    "Avcılar": ["Denizköşkler", "Ambarlı", "Cihangir", "Gümüşpala", "Firuzköy", "Merkez"],
    "Büyükçekmece": ["Mimaroba", "Sinanoba", "Kumburgaz", "Albatros", "Muratçeşme", "Tepecik"],
    "Çekmeköy": ["Taşdelen", "Mimar Sinan", "Merkez", "Alemdağ", "Ömerli", "Mehmet Akif"],
    "Tuzla": ["Mercan (Postane)", "Yayla", "Aydınlı", "İçmeler", "Şifa", "Tepeören"],
    "Sancaktepe": ["Sarıgazi", "Samandıra", "Yenidoğan", "Abdurrahmangazi", "Meclis"],
    "Sultanbeyli": ["Abdurrahmangazi", "Battalgazi", "Hasanpaşa", "Mehmet Akif", "Turgut Reis"],
    "Sultangazi": ["Cebeci", "Gazi Mah.", "50. Yıl", "Uğur Mumcu", "Esentepe"],
    "Esenler": ["Menderes", "Birlik", "Havaalanı", "Turgutreis", "Nine Hatun"],
    "Esenyurt": ["Akkoza (Koza)", "Mehterçeşme", "Güzelyurt", "Yeşilkent", "Pınar", "Örnek"],
    "Bağcılar": ["Güneşli", "Mahmutbey", "Kirazlı", "Yüzyıl", "Bağlar", "Göztepe"],
    "Bayrampaşa": ["Yıldırım", "Kocatepe", "Muratpaşa", "Kartaltepe", "Terzidere"],
    "Güngören": ["Merter", "Haznedar", "Güven", "Sanayi", "Akıncılar"],
    "Adalar": ["Büyükada (Maden)", "Büyükada (Nizam)", "Heybeliada", "Burgazada", "Kınalıada"],
    "Şile": ["Şile Merkez", "Ağva", "Kandıra Yolu", "Balibey", "Çavuş"],
    "Silivri": ["Silivri Sahil (Piri Mehmet)", "Semizkumlar", "Selimpaşa", "Gümüşyaka", "Değirmenköy"],
    "Çatalca": ["Kale Mah.", "Ferhatpaşa", "Binkılıç", "Kestanelik", "Çakıl"],
    "Arnavutköy": ["Hadımköy", "Bolluca", "Taşoluk", "Haraççı", "Merkez"]
}

# Prestijli/popüler mahalleler için birim fiyat çarpanları (Lüks lokasyon etkisi)
NEIGHBORHOOD_PREMIUMS = {
    "Bebek": 1.50, "Etiler": 1.40, "Levent": 1.35, "Ulus": 1.35, "Nişantaşı (Teşvikiye)": 1.40,
    "Caddebostan": 1.35, "Fenerbahçe": 1.40, "Moda (Caferağa)": 1.30, "Suadiye": 1.30,
    "İstinye": 1.35, "Yeniköy": 1.40, "Tarabya": 1.30, "Zekeriyaköy": 1.25, "Florya (Şenlikköy)": 1.35,
    "Yeşilköy": 1.30, "Ataköy": 1.25, "Kuzguncuk": 1.30, "Kandilli": 1.35, "Beylerbeyi": 1.25,
    "Batı Ataşehir": 1.25, "Göktürk": 1.30, "Bahçeşehir 1. Kısım": 1.20, "Atakent": 1.15
}
